pkg/kernel/link.go

* add idempotent wrapper for netlink library
* add utilities for finding netlink interfaces representing host
devices, e.g. SR-IOV virtual functions
Signed-off-by: Przemyslaw Lal <przemyslawx.lal@intel.com>

add kernel interface manipulation utilities

---

.github/workflows/ci.yaml

Update PRs are not getting auto merged, because there is no CI auto merge action.
✓ Added
Some CI checks, test runs are disabled / not added in ci.yaml.
✓ Enabled
✓ Added

Fix CI issues

---

pkg/kernel/networkservice/inject/client.go
pkg/kernel/networkservice/inject/common.go
pkg/kernel/networkservice/inject/server.go
pkg/kernel/networkservice/rename/client.go
pkg/kernel/networkservice/rename/common.go
pkg/kernel/networkservice/rename/server.go

This commit attempts to provide rename and inject veth or VF interface
facility for endpoint pod container.
Fixes #226 
Signed-off-by: Periyasamy Palanisamy <periyasamy.palanisamy@est.tech>

add interface rename and inject client chain element

---

.github/workflows/update-dependent-repositories-gomod.yaml

Because otherwise we get failures like:
https://github.com/networkservicemesh/sdk-kernel/runs/3214841353?check_suite_focus=true
Which are related to:
https://github.com/influxdata/telegraf/issues/8800
Signed-off-by: Ed Warnicke <hagbard@gmail.com>

Switch to using GOPRIVATE instead of GOPROXY

---

.github/workflows/release.yaml
.github/workflows/update-dependent-repositories-gomod.yaml

for go.mod version updates, this would be useful once this [pr](https://github.com/networkservicemesh/sdk-ovs/pull/1) is merged.
Signed-off-by: Periyasamy Palanisamy <periyasamy.palanisamy@est.tech>

add sdk-ovs as dependent repo

---

.github/workflows/release.yaml
.github/workflows/update-dependent-repositories-gomod.yaml

Though `sdk-ovs `repo depends on `sdk-kernel`  and `sdk-sriov` repos, but this dependency is addressed with this [PR](https://github.com/networkservicemesh/sdk-sriov/pull/232) which creates a chain `sdk-kernel -> sdk-sriov -> sdk-ovs` dependency, so there is no need of direct dependency with sdk-kernel.
Signed-off-by: Periyasamy Palanisamy <periyasamy.palanisamy@est.tech>

remove sdk-ovs as dependent repo for sdk-kernel

---

pkg/kernel/networkservice/inject/common.go

this commit fixes `Device or resource busy` error while renaming
interface back into its original name
Signed-off-by: Periyasamy Palanisamy <periyasamy.palanisamy@est.tech>

fix for interface renaming

---

pkg/kernel/networkservice/inject/common.go
pkg/kernel/networkservice/vfconfig/metadata.go

This would properly move back VF into host net namespace when NSE pod is deleted prematurely even before forwarder sends service close request.
Fixes #333

keep nse container net ns open until inject connection close is done

---

pkg/kernel/networkservice/connectioncontextkernel/ipcontext/ipaddress/common.go

Fully reads channel with input from `netlink.addrSubscribeAt` to fix goroutines leak in `ipaddress`.
`netlink.addrSubscribeAt` does almost the following behavior:
```
go func() {
defer close(ch)
for isNotClosed(done) {
ch <- doSomething()
}
}()
```
So the error currently is happening is `ch` not fully read after the `close(done)`, so this goroutine blocks on send and cannot return.
```
goroutine profile: total 5185
5146 @ 0x43aa65 0x4059fa 0x405755 0xd22279 0x471c61
#	0xd22278	github.com/vishvananda/netlink.addrSubscribeAt.func2+0x538	/root/go/pkg/mod/github.com/vishvananda/netlink@v1.1.0/addr_linux.go:405
```

[qfix] Fix goroutine leak in ipaddress

---

pkg/kernel/networkservice/connectioncontextkernel/ipcontext/ipaddress/common.go

Continues #342. Reads `ch` in separate goroutine.
https://github.com/networkservicemesh/sdk-kernel/pull/342#issuecomment-934420582

[qfix] Read ch in a goroutine

---

pkg/kernel/networkservice/connectioncontextkernel/ipcontext/ipneighbors/client.go
pkg/kernel/networkservice/connectioncontextkernel/ipcontext/ipneighbors/common.go
pkg/kernel/networkservice/connectioncontextkernel/ipcontext/ipneighbors/server.go
pkg/kernel/tools/peer/metadata.go

Issue: https://github.com/networkservicemesh/integration-k8s-gke/issues/215
Description is here - https://github.com/networkservicemesh/integration-k8s-gke/issues/215#issuecomment-1018200313
This PR moves kernel part of `ip neighbor` from `sdk-vpp `to `sdk-kernel`
`sdk-vpp` PR - https://github.com/networkservicemesh/sdk-vpp/pull/491

Add peer neighbor setting

---

go.mod
go.sum
pkg/kernel/networkservice/routelocalnet/server.go

Signed-off-by: Sergey Shlyanin <sergey.shlyanin@xored.com>
#464

Add routerlocalnet server chain element

---

pkg/kernel/tools/heal/liveness_check.go

Motivation:
1. If we add +1 [here](https://github.com/networkservicemesh/sdk-kernel/blob/main/pkg/kernel/tools/heal/liveness_check.go#L50), we unreasonably reduce the timeout (up to 2 times)
2. We cover this [select](https://github.com/networkservicemesh/sdk-kernel/blob/main/pkg/kernel/tools/heal/liveness_check.go#L85-L90) using `pinger.Timeout` [here](https://github.com/networkservicemesh/sdk-kernel/blob/main/pkg/kernel/tools/heal/liveness_check.go#L69)
3. We need to set `pinger.Interval`, because by default it is 1s.

Fix liveness check

---

pkg/kernel/tools/heal/liveness_check.go

Related issue: networkservicemesh/cmd-nsc#447
Return from LivenessCheck if no dst addresses set in the context
Signed-off-by: Laszlo Kiraly <laszlo.kiraly@est.tech>

Data path healing should be disabled

---

go.mod
go.sum
pkg/kernel/networkservice/connectioncontextkernel/ipcontext/ipaddress/common.go

Because of: https://github.com/vishvananda/netlink/pull/741
Issue: https://github.com/networkservicemesh/cmd-forwarder-vpp/issues/656

Update netlink version

---

pkg/kernel/networkservice/connectioncontextkernel/ipcontext/iprule/heal.go
pkg/kernel/networkservice/connectioncontextkernel/ipcontext/iprule/server.go

When a forwarder was restarting, the handled table IDs by the forwarded
were forgotten which caused duplicated tables/rules/routes in the pod
and potentially left routes which could cause traffic disturbances in
some cases.
Now, the forwarder is checking if the tables which exist in the pod are
corresponding to the requested policies before creating any other ones.
In case such tables exist, the forwarder will consider it as its own
table.
https://github.com/networkservicemesh/sdk-kernel/issues/426

Improve resiliency on ip context policy routes

---

pkg/kernel/networkservice/ethernetcontext/vf_client.go
pkg/kernel/networkservice/ethernetcontext/vf_common.go
pkg/kernel/networkservice/ethernetcontext/vf_server.go

Issue: https://github.com/networkservicemesh/sdk-sriov/issues/489
**Description:**
This PR fixes the following problems:
1. `vfEthernetContextServer` has to create VFs **_after_** next.Request, because the following elements (endpoint) can change the `ethernetcontext` that we are using inside `vfCreate`
2. It would be better if we set the VFs to their default state on Close (added `vfCleanup`)
3. Added logs

Fixes for ethernetcontext/vf

---

pkg/kernel/link.go
pkg/kernel/networkservice/inject/common.go

Issue: https://github.com/networkservicemesh/integration-k8s-packet/issues/320
Main changes:
1. Got rid of redundant `nshandle.RunIn()`. Much easier to use `netlink.NewHandleAt()`
2. Don't up an interface on Close (`moveToHostNetNS`)
3. Try to move the vf to the host namespace, if we get an error from `moveToContNetNS`
4. Fixed unsafe work with namespaces in `FindHostDevice`

Fix for working with network namespaces

---

pkg/kernel/tools/heal/liveness_check.go
pkg/kernel/tools/heal/liveness_check_test.go

Closes: https://github.com/networkservicemesh/integration-k8s-packet/issues/306
Now we specify the source address to determine which interface to use for checking.
Moved the check to goroutines, because with several addresses (src and dst) it is incorrect to divide the timeout.

use source address for ping to check if the connection is alive

---

pkg/kernel/networkservice/pinggrouprange/client.go
pkg/kernel/networkservice/pinggrouprange/common.go
pkg/kernel/networkservice/pinggrouprange/doc.go
pkg/kernel/networkservice/pinggrouprange/server.go
pkg/kernel/tools/heal/liveness_check.go

Issue: https://github.com/networkservicemesh/deployments-k8s/issues/9218
We use ping to check the liveliness of the connection. In order not to use the root privileges, we need to set the `/proc/sys/net/ipv4/ping_group_range` value. It allows to create the `SOCK_DGRAM` socket type (instead of `SOCK_RAW`) for ping and thus use it in non-privileged mode.

Use livelinesschecker in non-privileged mode

---

pkg/kernel/networkservice/connectioncontextkernel/ipcontext/iprule/common.go
pkg/kernel/networkservice/connectioncontextkernel/ipcontext/iprule/heal.go

Related issue: networkservicemesh/deployments-k8s/issues/9463
Fix for faulty ip rules after forwarder restart
Using proper key in internal Map for routing table IDs; Ensure that the routing table belongs to the link handled by NSM; At policy recovery do not flush the routing table if more than one rule reffering to it,
deleting the last rule with reference to a given routing table will flush the table.

Improved recovery for policy base routing

---

pkg/kernel/networkservice/connectioncontextkernel/ipcontext/iprule/common.go
pkg/kernel/networkservice/connectioncontextkernel/ipcontext/iprule/heal.go
pkg/kernel/networkservice/connectioncontextkernel/ipcontext/iprule/nsrtnextid.go
pkg/kernel/networkservice/connectioncontextkernel/ipcontext/iprule/server.go

Alternative fix for https://github.com/networkservicemesh/sdk-kernel/pull/603
`nsRTableNextIDToConnID` map is used as _**"mutex"**_ for a specific table ID within the netns of one client. 
How it works now (simplistically):
1. tableID = getFreeTableID()
2. nsRTableNextIDToConnID.Store(tableID)
3. Call `addPolicy` - it deletes the entry from the `nsRTableNextIDToConnID` after execution.
In these steps we can get the race condition. If several requests received `tableID=5` in the first step, then one of the requests added rules and cleared the map, then other requests also have a chance to use the same table ID.
I think we should clear `nsRTableNextIDToConnID` only after [flushing a table](https://github.com/networkservicemesh/sdk-kernel/blob/main/pkg/kernel/networkservice/connectioncontextk …

Fix work with nsRTableNextIDToConnID

---

pkg/kernel/networkservice/connectioncontextkernel/ipcontext/iprule/common.go

If flushing the table in delRule fails, the table with the stored id and the connection id will still contain the table id and the rule will still be existing.
Selecting a table ID based on routes and rules prevents conflicts to happen.

Policy Route: Select table ID based on routes and rules

---

pkg/kernel/networkservice/connectioncontextkernel/ipcontext/iprule/common.go

On Deletion, the default route got its dst attribute replaced with an empty IPv4 address even with IPv6.

Fix Deletion of IPv6 default policy routes

---

pkg/kernel/networkservice/inject/client.go
pkg/kernel/networkservice/inject/common.go
pkg/kernel/networkservice/inject/server.go

Move any orphan nsm interface to host namespace and delete it.
Related issue: networkservicemesh/deployments-k8s#9778

Fix interface cleanup

---

pkg/kernel/networkservice/connectioncontextkernel/ipcontext/iprule/common.go
pkg/kernel/networkservice/connectioncontextkernel/ipcontext/iprule/heal.go

Issue: https://github.com/networkservicemesh/sdk-kernel/issues/685
Try to delete the rule even if the route deletion fails.
For example when the belonging interface is deleted in parallel.

Fix Missing Policy Routes

---

.github/workflows/automerge.yaml

This PR disables the automerge workflow for pull requests opened by dependabot.

Disable automerge workflow for dependabot
