go.mod, go.sum, pkg/kernel/networkservice/connectioncontext/ethernetcontext/server.go, pkg/kernel/networkservice/connectioncontext/ipcontext/server.go, pkg/kernel/networkservice/connectioncontext/server.go, pkg/kernel/networkservice/inject/server.go, pkg/kernel/networkservice/rename/server.go, pkg/kernel/networkservice/vfconfig/context.go, pkg/kernel/utils/ns_switch.go
1. Rework inject chain element using NSSwitch
2. Add connection context chain elements
3. Add rename chain element
=> Add chain elements

.github/workflows/ci.yaml
https://github.com/networkservicemesh/sdk-kernel/pull/53/checks?check_run_id=1321797254
=> Fix update-dependent-repositories job

go.mod, go.sum, pkg/kernel/networkservice/inject/server.go
=> Update to new logger usage

go.mod, go.sum, pkg/kernel/networkservice/inject/server.go
=> Update to latest sdk version

go.mod, go.sum, pkg/kernel/networkservice/ipcontext/server.go
https://github.com/networkservicemesh/api/pull/47
Signed-off-by: Ed Warnicke <hagbard@gmail.com>
=> Adapt to multi-ip shift in API networkservicemesh/api#47

.github/workflows/ci.yaml, .github/workflows/release.yaml, .github/workflows/update-dependent-repositories-gomod.yaml
Signed-off-by: denis-tingajkin <denis.tingajkin@xored.com>
=> feat: Add release action

go.mod, go.sum, pkg/kernel/networkservice/connectioncontextkernel/ipcontext/ipaddress/common.go, pkg/kernel/networkservice/connectioncontextkernel/ipcontext/ipneighbors/common.go, pkg/kernel/networkservice/connectioncontextkernel/ipcontext/routes/common.go, pkg/kernel/networkservice/connectioncontextkernel/mtu/common.go, pkg/kernel/networkservice/inject/server.go, pkg/kernel/networkservice/rename/server.go
=> Manual api update

.github/workflows/release.yaml
Signed-off-by: Ed Warnicke <hagbard@gmail.com>
=> Add sdk-vpp to release dependencies.

pkg/kernel/networkservice/connectioncontextkernel/ipcontext/routes/common.go
Fixes:
https://github.com/networkservicemesh/sdk-kernel/issues/354
Signed-off-by: Ed Warnicke <hagbard@gmail.com>
=> Fix bug for non-/32 routes

pkg/kernel/link.go, pkg/kernel/networkservice/ethernetcontext/vf_client.go, pkg/kernel/networkservice/ethernetcontext/vf_common.go, pkg/kernel/networkservice/ethernetcontext/vf_server.go
Fixed search for link by PCI address in pci devices subdirectories
Signed-off-by: Laszlo Kiraly <laszlo.kiraly@est.tech>
=> Add vlan remote mechanism support (see networkservicemesh/sdk-vpp#399)

pkg/kernel/networkservice/connectioncontextkernel/server.go
Issue: https://github.com/networkservicemesh/api/issues/119
=> [qfix] Add iprule to connectioncontextkernel

.golangci.yaml, pkg/kernel/const_linux.go, pkg/kernel/link.go, pkg/kernel/networkservice/connectioncontextkernel/client.go, pkg/kernel/networkservice/connectioncontextkernel/ipcontext/ipaddress/client.go, pkg/kernel/networkservice/connectioncontextkernel/ipcontext/ipaddress/common.go, pkg/kernel/networkservice/connectioncontextkernel/ipcontext/ipaddress/server.go, pkg/kernel/networkservice/connectioncontextkernel/ipcontext/ipneighbors/client.go, pkg/kernel/networkservice/connectioncontextkernel/ipcontext/ipneighbors/common.go, pkg/kernel/networkservice/connectioncontextkernel/ipcontext/ipneighbors/server.go, pkg/kernel/networkservice/connectioncontextkernel/ipcontext/iprule/common.go, pkg/kernel/networkservice/connectioncontextkernel/ipcontext/iprule/server.go, pkg/kernel/networkservice/connectioncontextkernel/ipcontext/routes/client.go, pkg/kernel/networkservice/connectioncontextkernel/ipcontext/routes/common.go, pkg/kernel/networkservice/connectioncontextkernel/ipcontext/routes/server.go, pkg/kernel/networkservice/connectioncontextkernel/mtu/client.go, pkg/kernel/networkservice/connectioncontextkernel/mtu/common.go, pkg/kernel/networkservice/connectioncontextkernel/mtu/server.go, pkg/kernel/networkservice/connectioncontextkernel/server.go, pkg/kernel/networkservice/ethernetcontext/vf_client.go, pkg/kernel/networkservice/ethernetcontext/vf_common.go, pkg/kernel/networkservice/ethernetcontext/vf_server.go, pkg/kernel/networkservice/inject/client.go, pkg/kernel/networkservice/inject/common.go, pkg/kernel/networkservice/inject/server.go, pkg/kernel/tools/peer/metadata.go
Closes https://github.com/networkservicemesh/sdk-kernel/issues/438
=> Fix golangci-lint job

go.mod, go.sum, pkg/kernel/networkservice/setiptables4nattemplate/server.go
Signed-off-by: Sergey Shlyanin <sergey.shlyanin@xored.com>
Add `setiptables4nattemplate` chain element that sets provided template to kernel mechanism. 
#463
=> Add setiptables4nattemplate chain element

go.mod, go.sum, pkg/kernel/tools/heal/liveness_check.go
=> [qfix] Use another ping library for KernelLivenessCheck function

pkg/kernel/tools/heal/liveness_check.go
=> [qfix] Fix kernel ping

.github/workflows/release.yaml, .github/workflows/update-dependent-repositories-gomod.yaml
=> [qfix] Add cmd-nse-istio-proxy to dependent repositories

.github/workflows/automerge.yaml, .github/workflows/ci.yaml, .github/workflows/codeql-analysis.yml, .github/workflows/pr-for-updates.yaml, .github/workflows/release.yaml, .github/workflows/update-dependent-repositories-gomod.yaml
https://github.com/networkservicemesh/.github/issues/4
=> Reusable workflows

.github/workflows/release.yaml, pkg/kernel/tools/nshandle/ns_handle_linux_test.go
=> Fix reusable workflows

.github/workflows/release.yaml, .github/workflows/update-dependent-repositories-gomod.yaml
=> Add cmd-nse-l7-proxy to dependent repositories

pkg/kernel/const.go, pkg/kernel/networkservice/connectioncontextkernel/client.go, pkg/kernel/networkservice/connectioncontextkernel/ipcontext/ipaddress/client.go, pkg/kernel/networkservice/connectioncontextkernel/ipcontext/ipaddress/server.go, pkg/kernel/networkservice/connectioncontextkernel/ipcontext/routes/client.go, pkg/kernel/networkservice/connectioncontextkernel/ipcontext/routes/server.go, pkg/kernel/networkservice/connectioncontextkernel/mtu/client.go, pkg/kernel/networkservice/connectioncontextkernel/mtu/server.go, pkg/kernel/networkservice/connectioncontextkernel/server.go
Signed-off-by: Vyacheslav Tumanov <me@slavatumanov.me>
=> Fix linter issues after update golangci-lint version

.github/workflows/automerge.yaml
=> Add token to automerge workflow

pkg/kernel/networkservice/pinggrouprange/client.go, pkg/kernel/networkservice/pinggrouprange/common.go, pkg/kernel/networkservice/pinggrouprange/server.go
Issue: https://github.com/networkservicemesh/deployments-k8s/issues/9218
Code review: https://github.com/networkservicemesh/sdk-kernel/pull/589
=> pinggrouprange: fix code review comments

pkg/kernel/networkservice/connectioncontextkernel/ipcontext/ipaddress/common.go
https://github.com/networkservicemesh/deployments-k8s/issues/9216
=> Disable linter for channel reading loop

pkg/kernel/networkservice/connectioncontextkernel/pinggrouprange/common.go
Issue: https://github.com/networkservicemesh/deployments-k8s/issues/9726
=> Change message log level
